name: Deploy MkDocs

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # Install MkDocs and Material theme
      - run: pip install mkdocs mkdocs-material
      # Deploy site to GitHub Pages
      - run: mkdocs gh-deploy --force
